/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package java_assignment;

import java.io.BufferedReader;
import java.io.File;
import java.io.FileNotFoundException;
import java.io.FileReader;
import java.io.FileWriter;
import java.io.IOException;
import java.io.PrintWriter;
import java.util.Scanner;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import javax.swing.RowFilter;
import javax.swing.table.DefaultTableModel;
import javax.swing.table.TableRowSorter;

/**
 *
 * @author Vincent Leong
 */
public class Admin_Customer extends javax.swing.JFrame {

    /**
     * Creates new form 
     */
    public Admin_Customer() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        CustomerManageTable = new javax.swing.JTable();
        jLabel1 = new javax.swing.JLabel();
        UserName = new javax.swing.JLabel();
        CUsername = new javax.swing.JTextField();
        FirstName = new javax.swing.JLabel();
        CFname = new javax.swing.JTextField();
        LastName = new javax.swing.JLabel();
        CLname = new javax.swing.JTextField();
        DOB = new javax.swing.JLabel();
        CDOB = new javax.swing.JTextField();
        Password = new javax.swing.JLabel();
        CPWD = new javax.swing.JTextField();
        MPHnum = new javax.swing.JLabel();
        CPHnum = new javax.swing.JTextField();
        Addres = new javax.swing.JLabel();
        Cadr = new javax.swing.JTextField();
        role = new javax.swing.JLabel();
        Crole = new javax.swing.JTextField();
        ButtonADD = new javax.swing.JButton();
        ButtonSearch = new javax.swing.JButton();
        ButtonEdit = new javax.swing.JButton();
        ButtonDel = new javax.swing.JButton();
        ButtonLogout = new javax.swing.JButton();
        Gender = new javax.swing.JLabel();
        CGender = new javax.swing.JTextField();
        ButtonView = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        CustomerManageTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null}
            },
            new String [] {
                "Username", "Fname", "Lname", "Gender", "DOB", "Password", "Phone_number", "address", "role"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                true, true, false, true, true, true, true, true, true
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane1.setViewportView(CustomerManageTable);

        jLabel1.setText("Customer Manage Account");

        UserName.setText("UserName");

        CUsername.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CUsernameActionPerformed(evt);
            }
        });

        FirstName.setText("FirstName");

        LastName.setText("LastName");

        DOB.setText("Date of Birth");

        Password.setText("Password");

        MPHnum.setText("Phone number");

        Addres.setText("Address");

        role.setText("role");

        ButtonADD.setText("ADD");
        ButtonADD.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ButtonADDActionPerformed(evt);
            }
        });

        ButtonSearch.setText("Search");
        ButtonSearch.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ButtonSearchActionPerformed(evt);
            }
        });

        ButtonEdit.setText("Edit");
        ButtonEdit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ButtonEditActionPerformed(evt);
            }
        });

        ButtonDel.setText("Delete");

        ButtonLogout.setText("Logout");
        ButtonLogout.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ButtonLogoutActionPerformed(evt);
            }
        });

        Gender.setText("Gender");

        ButtonView.setText("View");
        ButtonView.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ButtonViewActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane1, javax.swing.GroupLayout.Alignment.TRAILING)
            .addGroup(layout.createSequentialGroup()
                .addGap(29, 29, 29)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel1)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(LastName, javax.swing.GroupLayout.PREFERRED_SIZE, 58, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(CLname))
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                                .addComponent(FirstName, javax.swing.GroupLayout.PREFERRED_SIZE, 58, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(CFname))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(UserName)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(CUsername, javax.swing.GroupLayout.PREFERRED_SIZE, 97, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(67, 67, 67)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(DOB, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(Password, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(MPHnum, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(CDOB)
                            .addComponent(CPWD)
                            .addComponent(CPHnum, javax.swing.GroupLayout.DEFAULT_SIZE, 91, Short.MAX_VALUE))
                        .addGap(42, 42, 42)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addComponent(Addres, javax.swing.GroupLayout.DEFAULT_SIZE, 64, Short.MAX_VALUE)
                                .addComponent(role, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                            .addComponent(Gender))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(Cadr, javax.swing.GroupLayout.DEFAULT_SIZE, 94, Short.MAX_VALUE)
                            .addComponent(Crole)
                            .addComponent(CGender)))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(ButtonADD)
                        .addGap(30, 30, 30)
                        .addComponent(ButtonSearch)
                        .addGap(38, 38, 38)
                        .addComponent(ButtonEdit)
                        .addGap(29, 29, 29)
                        .addComponent(ButtonDel)
                        .addGap(18, 18, 18)
                        .addComponent(ButtonView)))
                .addContainerGap(143, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(ButtonLogout)
                .addGap(35, 35, 35))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addGap(18, 18, 18)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 138, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(CPWD, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(Addres, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(Cadr, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(2, 2, 2))
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(UserName)
                                .addComponent(CUsername, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(DOB, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(CDOB, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(role, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(Crole, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(FirstName)
                                .addComponent(CFname, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(Password)))))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(LastName)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(CLname, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(MPHnum)
                        .addComponent(CPHnum, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(Gender)
                        .addComponent(CGender, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(58, 58, 58)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(ButtonADD)
                    .addComponent(ButtonSearch)
                    .addComponent(ButtonEdit)
                    .addComponent(ButtonDel)
                    .addComponent(ButtonView))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 72, Short.MAX_VALUE)
                .addComponent(ButtonLogout)
                .addGap(22, 22, 22))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void CUsernameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CUsernameActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_CUsernameActionPerformed

    private void ButtonADDActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ButtonADDActionPerformed
        // TODO add your handling code here:
        String username = CUsername.getText();
        String fname  =  CFname.getText();
        String lname  = CLname.getText();
        String dob  =  CDOB.getText();
        String pwd  = CPWD.getText();
        String phnum = CPHnum.getText();
        String adr = Cadr.getText();
        String role = Crole.getText();
        String gender = CGender.getText();
        
        boolean duplicate = false;
        
        try {
            File f = new File("ManageAccCustomer.txt");
             Scanner s = new Scanner(f);
             while(s.hasNextLine()){
                 String row = s.nextLine();
                 String data[] = row.split(",");
                 if(data[0].equals(username))
                   {
                     duplicate = true;
                     break;
                 }
             }
        } catch (FileNotFoundException ex){
            
        }
        if(duplicate){
            JOptionPane.showMessageDialog(this,"Username has been taken, plase use another username.");
        }else{
            try{
            PrintWriter p = new PrintWriter (new FileWriter("ManageAccCustomer.txt",true));
            p.println(username + "," + fname + "," + lname + "," + gender + "," + dob +"," + pwd + "," + phnum +"," + adr + "," + role);
            p.close();
        }   catch (IOException ex) {
                
            }
            JOptionPane.showMessageDialog(this,"Registration Successful.");
        }
    }//GEN-LAST:event_ButtonADDActionPerformed

    private void ButtonEditActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ButtonEditActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_ButtonEditActionPerformed

    private void ButtonLogoutActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ButtonLogoutActionPerformed
        // TODO add your handling code here:
          AdminMainMenu i =  new AdminMainMenu ();
                   i.setVisible(true);
                   this.setVisible(false);
    }//GEN-LAST:event_ButtonLogoutActionPerformed

    private void ButtonViewActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ButtonViewActionPerformed
        // TODO add your handling code here:
        DefaultTableModel table = (DefaultTableModel) CustomerManageTable.getModel();
        table.setRowCount(0);
        String search = CFname.getText();
        
        TableRowSorter<DefaultTableModel> sort = new TableRowSorter<> (table);
        CustomerManageTable.setRowSorter(sort);
        sort.setRowFilter(RowFilter.regexFilter(search));
        table.setRowCount(0);
        try{
            FileReader f = new FileReader ("ManageAccCustomer.txt");
            BufferedReader b = new BufferedReader(f);
            String reader = b.readLine();
            while((reader = b.readLine())!=null)
            {
                table.addRow(reader.split(","));
                
            }
            b.close();
           
        } catch (Exception e) {
            JOptionPane.showMessageDialog(null,"Error");
        }
            
        
    }//GEN-LAST:event_ButtonViewActionPerformed

    private void ButtonSearchActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ButtonSearchActionPerformed
        // TODO add your handling code here:
        String searchUsername = CUsername.getText();
        String searchFname = CFname.getText();
        String searchRole = Crole.getText();
        boolean status = false;
        
        if ((!searchUsername.equals(""))&& (!searchFname.equals(""))&&(searchRole.equals(""))){
        }
            else if(!searchUsername.equals("")){
                    try{
                        File f = new File("ManageAccCustomer.txt");
                        Scanner sc = new Scanner(f);
                        DefaultTableModel model = (DefaultTableModel)CustomerManageTable.getModel();
                        int rowcount = model.getRowCount();
                        for (int i = rowcount - 1 ; i>= 0; i--){
                            model.removeRow(i);
                        }
                        sc.nextLine();
                        while(sc.hasNextLine()){
                            String data[] = sc.nextLine().split(",");
                            String Username = data[0];
                        if (searchUsername.equalsIgnoreCase(Username)){
                            CUsername.setText(data[0]);
                            CPWD.setText(data[1]);
                            CFname.setText(data[2]);
                            CLname.setText(data[3]);
                            CDOB.setText(data[4]);
                            CPWD.setText(data[5]);
                            CPHnum.setText(data[6]);
                            Cadr.setText(data[7]);
                            Crole.setText(data[8]);
                            
                            model.addRow(data);
                            status = true;
                            break;
                        }
                        }
                    } catch (FileNotFoundException ex) {
                Logger.getLogger(Admin_Customer.class.getName()).log(Level.SEVERE, null, ex);
            }
                    if(status == false){ JOptionPane.showMessageDialog(this, "no such thing");
                        
                    }
                    }
        
        
    }//GEN-LAST:event_ButtonSearchActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Admin_Customer.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Admin_Customer.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Admin_Customer.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Admin_Customer.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Admin_Customer().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel Addres;
    private javax.swing.JButton ButtonADD;
    private javax.swing.JButton ButtonDel;
    private javax.swing.JButton ButtonEdit;
    private javax.swing.JButton ButtonLogout;
    private javax.swing.JButton ButtonSearch;
    private javax.swing.JButton ButtonView;
    private javax.swing.JTextField CDOB;
    private javax.swing.JTextField CFname;
    private javax.swing.JTextField CGender;
    private javax.swing.JTextField CLname;
    private javax.swing.JTextField CPHnum;
    private javax.swing.JTextField CPWD;
    private javax.swing.JTextField CUsername;
    private javax.swing.JTextField Cadr;
    private javax.swing.JTextField Crole;
    private javax.swing.JTable CustomerManageTable;
    private javax.swing.JLabel DOB;
    private javax.swing.JLabel FirstName;
    private javax.swing.JLabel Gender;
    private javax.swing.JLabel LastName;
    private javax.swing.JLabel MPHnum;
    private javax.swing.JLabel Password;
    private javax.swing.JLabel UserName;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel role;
    // End of variables declaration//GEN-END:variables
}
