/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package java_assignment;

/**
 *
 * @author Vincent Leong
 */
public class ManagerOder extends javax.swing.JFrame {

    /**
     * Creates new form ManagerOder
     */
    public ManagerOder() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        MangerOderTable = new javax.swing.JTable();
        ButtonManagerAddO = new javax.swing.JButton();
        ButtonManagerDeleteO = new javax.swing.JButton();
        ButtonManagerEditO = new javax.swing.JButton();
        ButtonManagerSearchO = new javax.swing.JButton();
        ButtonManagerOderBack = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setText("Manager Oder");

        MangerOderTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Product ID", "Product Name", "Price", "Fragile"
            }
        ));
        jScrollPane1.setViewportView(MangerOderTable);

        ButtonManagerAddO.setText("Add");
        ButtonManagerAddO.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ButtonManagerAddOActionPerformed(evt);
            }
        });

        ButtonManagerDeleteO.setText("Detele");

        ButtonManagerEditO.setText("Edit");

        ButtonManagerSearchO.setText("Search");

        ButtonManagerOderBack.setText("Back");
        ButtonManagerOderBack.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ButtonManagerOderBackActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel1)
                            .addComponent(jScrollPane1)))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(237, 237, 237)
                        .addComponent(ButtonManagerAddO)
                        .addGap(18, 18, 18)
                        .addComponent(ButtonManagerDeleteO)
                        .addGap(27, 27, 27)
                        .addComponent(ButtonManagerEditO)
                        .addGap(18, 18, 18)
                        .addComponent(ButtonManagerSearchO)
                        .addGap(90, 90, 90)
                        .addComponent(ButtonManagerOderBack)))
                .addGap(59, 59, 59))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 99, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 283, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(ButtonManagerAddO)
                    .addComponent(ButtonManagerDeleteO)
                    .addComponent(ButtonManagerEditO)
                    .addComponent(ButtonManagerSearchO)
                    .addComponent(ButtonManagerOderBack))
                .addGap(37, 37, 37))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void ButtonManagerAddOActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ButtonManagerAddOActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_ButtonManagerAddOActionPerformed

    private void ButtonManagerOderBackActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ButtonManagerOderBackActionPerformed
        // TODO add your handling code here:
        ManagerMainMenu i =  new ManagerMainMenu ();
                   i.setVisible(true);
                   this.setVisible(false);
    }//GEN-LAST:event_ButtonManagerOderBackActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ManagerOder.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ManagerOder.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ManagerOder.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ManagerOder.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new ManagerOder().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton ButtonManagerAddO;
    private javax.swing.JButton ButtonManagerDeleteO;
    private javax.swing.JButton ButtonManagerEditO;
    private javax.swing.JButton ButtonManagerOderBack;
    private javax.swing.JButton ButtonManagerSearchO;
    private javax.swing.JTable MangerOderTable;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JScrollPane jScrollPane1;
    // End of variables declaration//GEN-END:variables
}
